# Generated by Django 4.1 on 2022-09-30 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nit',
            field=models.CharField(max_length=150, unique=True, verbose_name='NIT'),
        ),
    ]
