# Generated by Django 4.1 on 2022-09-06 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('nit', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='NIT')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('fecha_creacion_emp', models.DateField(auto_now=True)),
                ('nom_emp', models.CharField(max_length=25, verbose_name='Nombre Empresa')),
                ('sec_prod', models.CharField(max_length=25, verbose_name='Senctor Productivo')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('telefono', models.CharField(max_length=100, verbose_name='Telefono')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.BigAutoField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('nom_usu', models.CharField(max_length=20, unique=True, verbose_name='Nombre Usuario')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='E-mail')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('rol', models.CharField(max_length=20, verbose_name='Rol')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id_tr', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('tipo', models.CharField(max_length=50, verbose_name='Ingreso - Egreso')),
                ('fecha_tr', models.DateField(auto_now=True)),
                ('concepto', models.TextField(max_length=500, verbose_name='Concepto')),
                ('monto', models.IntegerField(max_length=20, verbose_name='Monto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaccion', to='gestiorTransaccional.user')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('nom_emp', models.CharField(max_length=25, verbose_name='Nombres')),
                ('ape_emp', models.CharField(max_length=25, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='E-mail')),
                ('telefono', models.CharField(max_length=10, verbose_name='Telefono')),
                ('fecha_creacion', models.DateField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Empresa', to='gestiorTransaccional.empresa')),
            ],
        ),
    ]
