# Generated by Django 4.1 on 2022-09-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiorTransaccional', '0002_alter_empresa_nit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nit',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
