# Generated by Django 4.1 on 2022-09-10 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestiorTransaccional', '0002_alter_empresa_nit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ad',
            field=models.IntegerField(default=None, verbose_name='ad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='id_emp',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='id', to='gestiorTransaccional.empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='monto',
            field=models.IntegerField(verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_user',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nom_usu',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Nombre Usuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=50, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(blank=True, max_length=20, verbose_name='Rol'),
        ),
    ]
