# Generated by Django 4.1 on 2022-09-10 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestiorTransaccional', '0003_user_ad_user_id_emp_alter_transaccion_monto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_emp',
        ),
    ]
