# Generated by Django 4.1 on 2022-09-10 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestiorTransaccional', '0004_remove_user_ad_remove_user_id_emp'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='id_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='User', to='gestiorTransaccional.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='nom_usu',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nombre Usuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(max_length=20, verbose_name='Rol'),
        ),
    ]
