# Generated by Django 4.1 on 2022-09-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiorTransaccional', '0005_empleado_id_user_alter_user_nom_usu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_user',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
