# Generated by Django 4.1 on 2022-09-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiorTransaccional', '0006_alter_user_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_user',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
