# Generated by Django 4.1 on 2022-09-10 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestiorTransaccional', '0007_alter_user_id_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='id_user',
        ),
        migrations.AddField(
            model_name='empleado',
            name='id_useer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to='gestiorTransaccional.user'),
            preserve_default=False,
        ),
    ]
