# Generated by Django 4.1 on 2022-09-10 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestiorTransaccional', '0008_remove_empleado_id_user_empleado_id_useer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='id_useer',
            new_name='id_user',
        ),
    ]
