# Generated by Django 4.1 on 2022-09-10 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestiorTransaccional', '0009_rename_id_useer_empleado_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='id_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestiorTransaccional.user'),
        ),
    ]
