# Generated by Django 4.1 on 2022-09-10 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiorTransaccional', '0010_alter_empleado_id_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rol',
        ),
        migrations.AddField(
            model_name='user',
            name='admin',
            field=models.BooleanField(null=True, verbose_name='Rol'),
        ),
    ]
